name: AirportTraficController
version: @version@
main: com.github.graycat27.atc.AirportTrafficController
api-version: 1.16
authors: [graycat27]
description: AirTrafficControl plugin with LunaChat
depend:
  - LunaChat
commands:
  airtrafficcontroller:
    description: ATC base command
  atc:
    description: ATC base command
